# Generated by Django 5.0.3 on 2024-05-04 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_delete_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="CustomUserProfile",
        ),
    ]
