# Generated by Django 5.0.3 on 2024-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_customuserprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserprofile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
