# Generated by Django 5.0.3 on 2024-04-17 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_cart_guest_session_id_alter_cart_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="guest_session_id",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=255, null=True
            ),
        ),
    ]
