# Generated by Django 5.0.3 on 2024-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Pending", "Order Pending"),
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                ],
                default="Order pending",
                max_length=20,
            ),
        ),
    ]
