# Generated by Django 5.0.3 on 2024-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_remove_order_status_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="guest_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="a8a30bb7277640458802d42bca74008f",
                max_length=255,
                null=True,
            ),
        ),
    ]
