# Generated by Django 5.0.3 on 2024-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_cart_guest_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="58975d5c3b2e4a0996e0f23e17e876d4",
                max_length=255,
                null=True,
            ),
        ),
    ]
