# Generated by Django 5.0.3 on 2024-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="986a972fde7f4e61ad9345923eabde55",
                max_length=255,
                null=True,
            ),
        ),
    ]
