# Generated by Django 5.0.3 on 2024-05-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="d99872bf22644747b3f6e86ad91e443d",
                max_length=255,
                null=True,
            ),
        ),
    ]
