# Generated by Django 5.0.3 on 2024-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="e6f3eed6907d4a94912d4adcdc252ca8",
                max_length=255,
                null=True,
            ),
        ),
    ]
