# Generated by Django 5.0.3 on 2024-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="0d623650dd3a41b7ac15e64c54b4b439",
                max_length=255,
                null=True,
            ),
        ),
    ]
