# Generated by Django 5.0.3 on 2024-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="29dde401a328416095071a9853b2c75c",
                max_length=255,
                null=True,
            ),
        ),
    ]
