# Generated by Django 5.0.3 on 2024-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0018_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="e8bad264144f4c469bf5144590920165",
                max_length=255,
                null=True,
            ),
        ),
    ]
