# Generated by Django 5.0.3 on 2024-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="7323d5b1f3ce46cfaa17ae8050108275",
                max_length=255,
                null=True,
            ),
        ),
    ]
