# Generated by Django 5.0.3 on 2024-05-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_order_guest_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.AlterField(
            model_name="order",
            name="guest_session_id",
            field=models.CharField(
                blank=True,
                default="171d4e6086714dffa8f749d92d82e84f",
                max_length=255,
                null=True,
            ),
        ),
    ]
