# Generated by Django 5.0.3 on 2024-03-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_category_parent_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_category",
                to="products.category",
            ),
        ),
    ]
