# Generated by Django 5.0.3 on 2024-04-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product_image_category_image_product_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(null=True, upload_to="subcatgeory_images/"),
        ),
    ]
