# Generated by Django 5.0.3 on 2024-04-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_subcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_policy",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_available",
                    models.CharField(
                        choices=[("In stock", "In stock"), ("Stock out", "Stock out")],
                        default="In stock",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
